# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2024 Z-Wave Alliance
# Demo copied from https://docs.github.com/en/actions/quickstart
name: Build and Test Z-Wave Tools Core

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

jobs:
  legal-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{  env.debian_packages }}
        env:
          debian_packages: reuse

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Legal check
        run: reuse lint

  build-and-test-z-wave-tools-core:
    runs-on: windows-latest
    env:
      Configuration: Release
      TargetPlatform: "Any CPU"
      Solution_Path: ${{ github.workspace}}\z-wave-tools-core\ZWaveDll.sln  
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout z-wave-tools-core
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ZWAVE_ACCESS_TOKEN }}
          path: 'z-wave-tools-core'

      # TODO: https://github.com/Z-Wave-Alliance/z-wave-tools-core/issues/5
      - name: Checkout z-wave-blobs
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ZWAVE_ACCESS_TOKEN }}
          repository: 'Z-Wave-Alliance/z-wave-blobs'
          path: 'z-wave-blobs'
          ref: 'v0.1.0'

      - name: Add MSBuild.exe to Path
        uses: microsoft/setup-msbuild@v1.1

      #- name: Add VSTest.Console.exe to Path
      #  uses: darenm/Setup-VSTest@v1.2

      - name: Restore NuGet Packages for Z-Wave Tools Core Solution
        run: |
          MSBuild.exe ${{env.Solution_Path}} -restore -verbosity:minimal

      - name: Build Z-Wave Tools Core Solution in Release
        env:
          Configuration: Release
        run: |
          MSBuild.exe ${{env.Solution_Path}} -property:Platform="${{env.TargetPlatform}}" -property:Configuration=${{env.Configuration}} -verbosity:minimal

      - name: Build Z-Wave Tools Core Solution in Debug
        env:
            Configuration: Debug
        run: |
          MSBuild.exe ${{env.Solution_Path}} -property:Platform="${{env.TargetPlatform}}" -property:Configuration=${{env.Configuration}} -verbosity:minimal

      #- name: Run NUnit Tests
      #  run: |
      #    vstest.console.exe /logger:$env:LOGGER_ARGS Tests\BasicApplicationTests\bin\Debug\BasicApplicationTests.dll
      #    vstest.console.exe /logger:$env:LOGGER_ARGS Tests\UtilsTests\bin\Debug\UtilsTests.dll
      #    vstest.console.exe /logger:$env:LOGGER_ARGS Tests\ZnifferApplicationTests\bin\Debug\ZnifferApplicationTests.dll
      #    vstest.console.exe /logger:$env:LOGGER_ARGS Tests\ZWaveTests\bin\Debug\ZWaveTests.dll
      #  env:
      #    LOGGER_ARGS: "console;verbosity=minimal"
