# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-FileCopyrightText: 2024 Z-Wave Alliance
# Demo copied from https://docs.github.com/en/actions/quickstart
name: Build and Test Z-Wave Tools Core

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test-z-wave-tools-core:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add MSBuild.exe to Path
        uses: microsoft/setup-msbuild@v1.1

      - name: Add VSTest.Console.exe to Path
        uses: darenm/Setup-VSTest@v1.2

      - name: Restore NuGet Packages for Z-Wave Tools Core Solution
        run: msbuild $env:Solution_Path -restore -verbosity:minimal

      - name: Build Z-Wave Tools Core Solution in Release
        run: |
          msbuild $env:Solution_Path -property:Platform=$env:TargetPlatform -property:Configuration=$env:Configuration -verbosity:minimal
        env:
          Configuration: Release
          Solution_Path: "ZWaveDll.sln"
          TargetPlatform: "Any CPU"

      - name: Build Z-Wave Tools Core Solution in Debug
        run: |
          msbuild $env:Solution_Path -p:Platform=$env:TargetPlatform -p:Configuration=$env:Configuration -verbosity:minimal
        env:
          Configuration: Debug
          Solution_Path: "ZWaveDll.sln"
          TargetPlatform: "Any CPU"

      - name: Run NUnit Tests
        run: |
          vstest.console.exe /logger:$env:LOGGER_ARGS Tests\BasicApplicationTests\bin\Debug\BasicApplicationTests.dll
          vstest.console.exe /logger:$env:LOGGER_ARGS Tests\UtilsTests\bin\Debug\UtilsTests.dll
          vstest.console.exe /logger:$env:LOGGER_ARGS Tests\ZnifferApplicationTests\bin\Debug\ZnifferApplicationTests.dll
          vstest.console.exe /logger:$env:LOGGER_ARGS Tests\ZWaveTests\bin\Debug\ZWaveTests.dll
        env:
          LOGGER_ARGS: "console;verbosity=minimal"
